name: AWS CLI
on:
  push:
    branches:
      - main

jobs:
  configure-sso:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up AWS credentials
        run: |
          echo "[default]
          aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}" > ~/.aws/credentials

      - name: Get up AWS credentials
        run: |
          ls -l ~/.aws/credentials

      - name: Your AWS CLI Command
        run: aws s3 ls  # Replace with your actual AWS CLI command
        env:
          AWS_REGION: us-west-1  # Specify your AWS region here        
        

# ## funzt ned !!
      # - name: Configure AWS credentials
        # uses: aws-actions/configure-aws-credentials@v4
# #        uses: aws-actions/configure-aws-credentials@v1
        # with:
            # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            # aws-region: us-east-1
        
## chatGPT lügt  - es gibt keine aws-actions/configure-aws-cli und wohl auch keine Parameter für "aws configure sso" !!!
      # - name: Configure AWS CLI
        # uses: aws-actions/configure-aws-cli@v2

        # with:
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-region: us-east-1

      # - name: Configure AWS CLI for SSO
        # run: |
          # aws configure sso \
            # --profile AndreasM-aws-sso-session \
            # --region us-east-1 \
            # --sso-start-url https://aqua-sso.awsapps.com/start# \
            # --sso-region us-east-1 \
            # --sso-account-id 633291361733 \
            # --sso-role-name aws-aqua-cross-dep-cs

          # aws sso login --profile AndreasM-aws-sso-session

      - name: Use SSO profile
        run: |
          aws s3 ls --profile aws-aqua-cross-dep-cs-633291361733
