name: AWS CLI
on:
  push:
    branches:
      - main

jobs:
  configure-sso:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v4
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        

      # - name: Configure AWS CLI
        # uses: aws-actions/configure-aws-cli@v2

        # with:
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-region: us-east-1

      # - name: Configure AWS CLI for SSO
        # run: |
          # aws configure sso \
            # --profile sso-profile \
            # --region us-east-1 \
            # --sso-start-url https://aqua-sso.awsapps.com/start# \
            # --sso-region us-east-1 \
            # --sso-account-id 633291361733 \
            # --sso-role-name aws-aqua-cross-dep-cs

          # aws sso login --profile sso-profile

      # - name: Use SSO profile
        # run: |
          # aws s3 ls --profile sso-profile
