name: AWS CLI
on:
  push:
    branches:
      - main

jobs:
  configure-sso:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up AWS credentials
        run: |
          mkdir ~/.aws/
          echo "[default]
          region                =   us-west-1
          aws_access_key_id     =   ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key =   ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token     =   ${{ secrets.AWS_SESSION_TOKEN }}" > ~/.aws/credentials

#     - name: Your AWS CLI Command
#        run: aws s3 ls  # Replace with your actual AWS CLI command
#        env:
#          AWS_REGION: us-west-1  # Specify your AWS region here
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: pull / push images to Amazon ECR
        id: build-image
        env:
          App_Image:        nginx
          ECR_REPOSITORY:   andreasm
          ECR_REGISTRY:     ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker pull $App_Image
          docker tag $App_Image $ECR_REGISTRY/$ECR_REPOSITORY:$App_Image
          docker images
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$App_Image
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$App_Image" >> $GITHUB_OUTPUT
